version: "3"
services:

  api-gateway:
    container_name: api-gateway
    build: api-gateway
    hostname: localhost
    network_mode: host
    restart: always
    ports:
      - 8080:8080


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017


  user-service:
    container_name: user-service
    build: user-service/
    ports:
      - 8085:8085
    links:
      - mongodb
    restart: always

  appointment-service:
    container_name: appointment
    build: appointment-service/
    ports:
      - 8081:8081
    links:
      - mongodb
    restart: always

  slot-service:
    container_name: slot-service
    build: slot-service/
    ports:
      - 8084:8084
    links:
      - mongodb
    restart: always

  email-service:
    container_name: email-service
    build: email-service/
    ports:
      - 8082:8082
    restart: always

  product-webapp-service:
    container_name: product-webapp-service
    build: product-webapp-service/
    restart: always
    ports:
      - 3000:3000

  product-webapp:
    container_name: product-webapp
    build: product-webapp/
    hostname: localhost
    network_mode: host
    restart: always
    ports:
      - 3000:3000

  video-chat-service:
    container_name: video-chat-service
    build: video-chat-service/
    ports:
      - 8083:8083
    restart: always

  socket-server:
    container_name: socket-server
    build: socket-server/
    hostname: localhost
    network_mode: host
    ports:
      - 5000:5000
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
