

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: appointment-service
          uri: http://localhost:8060/
          predicates:
            - Path=/api/v1/**
        - id: user-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/**
